### PR TITLE
Trents branch

### PR DESCRIPTION
**Pull request by thyer**
@Jacobtk Here's some code.

### CODE REVIEW

**Comment by Jacobtk** [comment]
Alright, here we go.

- Typo in the cityToCity .txt, shows one of the routes has a length of 22.
- How is the initial round set up? How are we enforcing that the first thing they do must be select destination cards? (Note: They must keep at least 2 of their initial destinations. Any time after that they can keep 1, 2, or 3. I don't think this is implemented)
- Number of locomotives. The set of rules I'm looking at says it should be 14 instead of 16.
- Double routes excluding for small number of players... We're adding that in later right?
- It appears that the train cards are not randomized initially.
- Will this logic work for buying gray Routes? Doesn't look like it.
- Buying routes defaults to using least number of wild cards. Is this how we want it? Should the user be able to specify which cards they use?
- The logic for canDrawTrainCard in the Game class looks off. Should be able to draw two cards during their turn, regardless of location. It also appears that the special visible locomotive rule is missing.
- Currently calling advanceTurn in getDestinations. Should it actually be in selectDestination?
- For drawing a card, where is drewAlreadyCurrentTurn being reset to false?
- In GameBoard's canDrawDestinationRoute, should allow player to draw destinations even if there are only one or two left.
- It is possible that buying a route completes a destination card. When should the points be calculated for that?
- How/where is the final round and end of game logic being handled? It is possible that buying a route triggers the final round and it is possible that any of the three turn options triggers the end of the game.

Hopefully I've caught everything. Having multiple canDo's in different classes for each operation made it somewhat difficult to keep track of what was being tested for where.

**Comment by GLeviRodriguez** [comment]
Looking through here, I notice you're returning a BadCredentialsException for both an invalid password and if a user is already logged in. Can we change this to have a separate exception (already logged in)?

**Comment by thyer** [comment]
Sorry for slowness, I'll make these fixes/respond to inquiries later this week

**Comment by thyer** [comment]
Double routes being reduced to one when there's only a few players won't be implemented until much later (it's not super important, and most people tend to ignore the rule anyway, plus a way to implement it isn't springing to mind).

**Comment by thyer** [comment]
I'm going to open an ongoing issue for indicating which cards should be used in BuyRoute. This will have to be done through the full stack and I don't have time for it quite yet.

**Comment by thyer** [comment]
For advancing turns, when we played, the players were allowed to wait until the next turn to actually pick which destination cards they wanted. So in that case, getting destination cards ended their turn, but before their next turn began, they needed to select the cards.

**Comment by thyer** [comment]
alreadyDrewCurrentTurn is reset to false in advanceTurn

**Comment by thyer** [comment]
destinationRoute completion...this is a hard one we haven't really discussed yet. Will discuss offline to find a solution. Difficulty comes because we can't calculate points until the end, but need to indicate to user in the client whether or not a given destination is reached.

**Comment by Jacobtk** [comment]
@thyer @GLeviRodriguez From what I can tell, most of this looks good. We obviously still need to fix the issue of knowing which cards to use in buying None routes, and we still need to nail down scoring. Other than that, the biggest issue I'm seeing right now has to do with getDestinations and selectDestinations.

Let me see if I'm understanding selectDestinations correctly. A player will first call getDestinations which will return a set of destinations to choose from and end their turn. Thus selectDestinations should be allowed to be called during someone else's turn (the Game class, at least, does not currently allow this). The player is required to call selectDestinations before their next turn will begin. If they have not called selectDestinations before the start of their next turn, no other operations will be allowed until they do (this still needs to be enforced somehow).
One other wrinkle to this set up might be the end of the game. It is possible that getting destinations is the last thing a player chooses to do and ends the game. In this case, the game should wait until they selectDestinations before ending the game because the destinations they select may effect their score.

Because of these issues I wonder if it might be easier to have the turn advance after the user calls selectDestinations rather than getDestinations. What do you guys think?

**Comment by thyer** [comment]
I agree with you, Jacob. Let's have the user select cards directly after
getting them - and ending the turn after selection.

Op zaterdag 27 februari 2016 heeft Jacobtk <notifications@github.com> het
volgende geschreven:

> @thyer <https://github.com/thyer> @GLeviRodriguez
> <https://github.com/GLeviRodriguez> From what I can tell, most of this
> looks good. We obviously still need to fix the issue of knowing which cards
> to use in buying None routes, and we still need to nail down scoring. Other
> than that, the biggest issue I'm seeing right now has to do with
> getDestinations and selectDestinations.
>
> Let me see if I'm understanding selectDestinations correctly. A player
> will first call getDestinations which will return a set of destinations to
> choose from and end their turn. Thus selectDestinations should be allowed
> to be called during someone else's turn (the Game class, at least, does not
> currently allow this). The player is required to call selectDestinations
> before their next turn will begin. If they have not called
> selectDestinations before the start of their next turn, no other operations
> will be allowed until they do (this still needs to be enforced somehow).
> One other wrinkle to this set up might be the end of the game. It is
> possible that getting destinations is the last thing a player chooses to do
> and ends the game. In this case, the game should wait until they
> selectDestinations before ending the game because the destinations they
> select may effect their score.
>
> Because of these issues I wonder if it might be easier to have the turn
> advance after the user calls selectDestinations rather than
> getDestinations. What do you guys think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bmcgary/TicketToRide/pull/5#issuecomment-189739445>.
>


-- 
Verzonden via mijn iPhone

**Comment by GLeviRodriguez** [comment]
I agree. Simplifies it a lot.

**Comment by thyer** [comment]
Done. Solving merge conflicts with master, and then merging.

**Pull request merged**
