### PR TITLE
Login server branch

### PR DESCRIPTION
**Pull request by thyer**
Need code review. Would somebody else take a look at what we've got here? Maybe someone on QA like @Jacobtk or chao?

### CODE REVIEW

**Comment by Jacobtk** [comment]
I'll take a look.

**Comment by Jacobtk** [comment]
@thyer 
So I'm still looking at the code more thoroughly, but I thought I should mention that, at least on my machine there appear to be quite a few errors. Many of them are quick fixes, like changing "import server.commands" to "import server.Commands". Are you seeing these errors too?

**Comment by Jacobtk** [comment]
So here are the things I found and a few questions:
-Player's addPoints function disregards the parameter passed in and just increments their score by 1.
-Player's addTrainCarCard looks like it wouldn't actually increase the number of cards.
-PlayerManager's canBuyTrackWithCards doesn't appear to take into account wilds.
-Register command returns null at bottom of execute. Return success instead.
-In ServerFacade, final line of code in canAddPlayerToGame should use < instead of <=
-We discussed at one point having the canDo methods actually be in the model facade. Did we decide against that?
-Are we still planning on only storing hashed passwords? If so, where is the hashing taking place? Server side or Client side? Is the password given the login and register functions hashed or not?
-ServerFacade's register function should probably include the call to addNewUser in the try block and an additional catch block written for the AddUserException
-I'll admit that I'm unfamiliar with the -> operator in Java. What is it? How are you using it?

**Comment by thyer** [comment]
Great points - I'll try and fix these this afternoon/tonight

**Comment by thyer** [comment]
I'll also try and answer your questions after some investigation.

**Comment by thyer** [comment]
Adding a new commit to address @Jacobtk 's remarks:

Point by point comments
**-Player's addPoints function disregards the parameter passed in and just increments their score by 1.**
fixed
**-Player's addTrainCarCard looks like it wouldn't actually increase the number of cards.**
fixed
**-PlayerManager's canBuyTrackWithCards doesn't appear to take into account wilds.**
that's correct, since wilds have to be specified by the user. 
**-Register command returns null at bottom of execute. Return success instead.**
@GLeviRodriguez may know more about this
**-In ServerFacade, final line of code in canAddPlayerToGame should use < instead of <=**
fixed
**-We discussed at one point having the canDo methods actually be in the model facade. Did we decide against that?**
there are quite a few in the GameBoard, but in general, I tried to follow the UML diagram (https://www.lucidchart.com/documents/edit/0b8238e4-ac97-4db0-8f4a-704e6c5b82be/0)
**-Are we still planning on only storing hashed passwords? If so, where is the hashing taking place? Server side or Client side? Is the password given the login and register functions hashed or not?**
I don't know. @GLeviRodriguez do you know?
**-ServerFacade's register function should probably include the call to addNewUser in the try block and an additional catch block written for the AddUserException**
in this case, I think we're justified in passing the exception up the stack since the AddUserException is only likely to be thrown if the user already exists. The improper instantiation is just me covering all the bases so we can get a more accurate error message in case it should happen (which I think is impossible as of right now). 
**-I'll admit that I'm unfamiliar with the -> operator in Java. What is it? How are you using it?**
I didn't see this in ServerFacade...it this from the command objects? I didn't see it anywhere.

**Comment by Jacobtk** [comment]
There are a couple places the -> is being used. For instance, on line 50 of ServerMain. I think it's a way to do a lambda expression of some kind, but like I said, I've never seen it in Java before.

**Comment by thyer** [comment]
@Jacobtk looks like the lambda bits were taken out. @GLeviRodriguez it looks like the most recent changes introduced conflicts. Do you want me to try and resolve them?

**Comment by GLeviRodriguez** [comment]
@thyer sure. I'll be out of hours after I finish the design doc, so if you could do that, it'd be appreciated.

**Comment by thyer** [comment]
@rayn33 @GLeviRodriguez I resolved all merge conflicts. Please make sure I didn't resolve them improperly, if you would.

**Comment by Jacobtk** [comment]
@thyer Everything looks good in this one, as far as I can tell.
I did have one more question though. Should we be checking everywhere that a particular user is logged in? (i.e. Do we ever use the loggedIn flag anywhere?)

**Comment by thyer** [comment]
Good point, put in a few extra checks using the flag (we already had it, just threw it in a few new places). I'm gonna merge the pull request now.

**Pull request merged**
