### PR TITLE
Levis branch

### PR DESCRIPTION
**Pull request by GLeviRodriguez**
@harkerd @thyer The latest changes to the commands. This implements StartGame and SendClientModelInfo. 

I have to apologize: the API is not up to date, and I will be updating that today or tomorrow. In essence, the start game command, instead of sending gameplay information in its response, instead sends a sendclientmodelinfo response upon starting a game.

Changes in this pull request made major modifications to the GameInfo class and its relatives.These classes mask the model classes, serving as DTOs for the client. GameInfo and PlayerInfo, which existed before, were broadened into a few subclasses to account for information differences between the lobby and actual gameplay. Additionally, gameplay player information is split into two different responses, one containing general information forwarded to all players and one containing that player's sensitive information (train cards, destination cards).

One method was updated in the server facade to be able to get a game by its id. The DTO classes take this game to generate the relevant information.

There were also a few changes made to increase code readability.

### CODE REVIEW

**Comment by thyer** [comment]
@GLeviRodriguez Let me know when the ServerFacade is ready for merging...there's a lot of weirdness going on in there right now

**Comment by GLeviRodriguez** [comment]
@thyer All excess changes have been removed from ServerFacade

**Comment by GLeviRodriguez** [comment]
The API has been updated; it should now be accurate for Game Lobby. There were a few changes; please let me know if these are unacceptable. I believe I've run all the changes through @harkerd or @kennygman. 

At this point, the new commands should reflect the API.

**Comment by thyer** [comment]
I approve.

**Comment by GLeviRodriguez** [comment]
Merged

**Pull request merged**
